#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.2
#  in conjunction with Tcl version 8.6
#    Feb 25, 2022 10:07:15 PM IST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import test1_support

import MySQLdb
mydb=MySQLdb.connect(host="localhost",user="root",password="root",port=3306)
mycursor=mydb.cursor()
mycursor.execute("use `yarn register`")
from tkcalendar import Calendar #cal
import modt
L1,L2,L3,L4,L5=[1,],[2,],[3,],[4,],[5,]
L1,L2,L3,L4,L5=modt.funclist(L1,L2,L3,L4,L5)
import os.path



def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    test1_support.set_Tk_var()
    top = Toplevel1 (root)
    test1_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    test1_support.set_Tk_var()
    top = Toplevel1 (w)
    test1_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1280x720+123+24")
        top.minsize(120, 1)
        top.maxsize(3076, 845)
        top.resizable(1,  1)
        top.title("Yarn Rec. Register")
        top.configure(background="#404040")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top
        self.combobox = tk.StringVar()
        self.combobox2 = tk.StringVar()
        self.combobox3 = tk.StringVar()
        self.combobox4 = tk.StringVar()

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.039, rely=0.278, height=44, width=47)
        self.Button1.configure(activebackground="#004080")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#0080c0")
        self.Button1.configure(command=test1_support.tbl)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#ffff00")
        photo_location = "../Users/Asvin/Desktop/outline_add_circle_white_24dp.png"
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Button1.configure(image=_img0)
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''ADD''')

        self.TCombobox1 = ttk.Combobox(self.top)
        self.TCombobox1.place(relx=0.133, rely=0.069, relheight=0.042
                , relwidth=0.125)
        self.value_list = L1
        self.TCombobox1.configure(values=self.value_list)
        self.TCombobox1.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.TCombobox1.configure(textvariable=test1_support.combobox1)
        self.combobox.set('''combobox''')
        self.TCombobox1.configure(background="#9e9e9e")
        self.TCombobox1.configure(takefocus="")
        self.TCombobox1.configure(cursor="fleur")

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(relx=0.289, rely=0.069, height=30, relwidth=0.097)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Courier New} -size 10 -weight bold")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="blue")
        self.Entry1.configure(selectforeground="white")
        self.Entry1.configure(textvariable=test1_support.rcd)

        self.Entry2 = tk.Entry(self.top)
        self.Entry2.place(relx=0.406, rely=0.069, height=30, relwidth=0.105)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="-family {Courier New} -size 10 -weight bold")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="blue")
        self.Entry2.configure(selectforeground="white")
        self.Entry2.configure(textvariable=test1_support.inv_num)

        self.Entry3 = tk.Entry(self.top)
        self.Entry3.place(relx=0.531, rely=0.069, height=30, relwidth=0.081)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="-family {Courier New} -size 10 -weight bold")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="blue")
        self.Entry3.configure(selectforeground="white")
        self.Entry3.configure(textvariable=test1_support.inv)

        self.Entry4 = tk.Entry(self.top)
        self.Entry4.place(relx=0.625, rely=0.069, height=30, relwidth=0.089)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="-family {Courier New} -size 10 -weight bold")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="blue")
        self.Entry4.configure(selectforeground="white")
        self.Entry4.configure(textvariable=test1_support.gr_num)

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.594, rely=0.153, height=34, width=99)
        self.Label1.configure(activebackground="#ffff00")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#737373")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''CARD NUM''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.039, rely=0.069, height=33, width=102)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#737373")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''BUYER''')

        self.Label3 = tk.Label(self.top)
        self.Label3.place(relx=0.305, rely=0.014, height=36, width=81)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#737373")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''RCD_DATE''')

        self.Label4 = tk.Label(self.top)
        self.Label4.place(relx=0.539, rely=0.014, height=34, width=84)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="#000000")
        self.Label4.configure(background="#737373")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label4.configure(foreground="#ffffff")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''INVOICE_DT''')

        self.Label5 = tk.Label(self.top)
        self.Label5.place(relx=0.477, rely=0.153, height=36, width=70)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#737373")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label5.configure(foreground="#ffffff")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''YARN_LOT''')

        self.TCombobox2 = ttk.Combobox(self.top)
        self.TCombobox2.place(relx=0.023, rely=0.208, relheight=0.042
                , relwidth=0.125)
        self.value_list = L2
        self.TCombobox2.configure(values=self.value_list)
        self.TCombobox2.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.TCombobox2.configure(textvariable=test1_support.combobox2)
        self.combobox2.set('''combobox2''')
        self.TCombobox2.configure(background="#9e9e9e")
        self.TCombobox2.configure(takefocus="")

        self.TCombobox3 = ttk.Combobox(self.top)
        self.TCombobox3.place(relx=0.164, rely=0.208, relheight=0.042
                , relwidth=0.125)
        self.value_list = L3
        self.TCombobox3.configure(values=self.value_list)
        self.TCombobox3.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.TCombobox3.configure(textvariable=test1_support.combobox3)
        self.combobox3.set('''combobox3''')
        self.TCombobox3.configure(background="#9e9e9e")
        self.TCombobox3.configure(takefocus="")

        self.TCombobox4 = ttk.Combobox(self.top)
        self.TCombobox4.place(relx=0.305, rely=0.208, relheight=0.042
                , relwidth=0.125)
        #self.TCombobox4.configure(postcommand="test1_support.cd")
        self.value_list = L4
        self.TCombobox4.configure(values=self.value_list)
        self.TCombobox4.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.TCombobox4.configure(textvariable=test1_support.combobox4)
        self.combobox4.set('''combobox4''')
        self.TCombobox4.configure(background="#9e9e9e")
        self.TCombobox4.configure(takefocus="")
        self.TCombobox4.bind("<Key-Return>",lambda x:[self.Entry1.focus_set(),test1_support.cd(1)])
        #self.TCombobox4.bind("<Key-Return>",test1_support.cd)
        #self.TCombobox4.bind("<FocusOut>",test1_support.cd)

        self.Label6 = tk.Label(self.top)
        self.Label6.place(relx=0.047, rely=0.167, height=24, width=108)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#737373")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label6.configure(foreground="#ffffff")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''YARN COUNT''')

        self.Label7 = tk.Label(self.top)
        self.Label7.place(relx=0.195, rely=0.167, height=24, width=93)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#737373")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label7.configure(foreground="#ffffff")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''YARN''')

        self.Label8 = tk.Label(self.top)
        self.Label8.place(relx=0.313, rely=0.167, height=23, width=139)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="#c0c0c0")
        self.Label8.configure(background="#737373")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label8.configure(foreground="#ffffff")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''SHADE NUMBER''')

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.008, rely=0.344, relheight=0.639
                , relwidth=0.988)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#000080")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.grid_columnconfigure(0, weight = 1)
        self.Frame1.grid_rowconfigure(0, weight = 1)

        self.cust1=test1_support.Custom(self.Frame1)
        self.cust1.enable_bindings()
        self.cust1.grid(row = 0, column = 0, sticky = "nswe")

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.938, rely=0.278, height=44, width=47)
        self.Button2.configure(activebackground="#008000")
        self.Button2.configure(activeforeground="white")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#00ff00")
        self.Button2.configure(command=test1_support.rfsh)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        photo_location = "../Users/Asvin/Desktop/outline_refresh_black_18dp.png"
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.Button2.configure(image=_img1)
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Button''')

        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.086, rely=0.278, height=44, width=47)
        self.Button3.configure(activebackground="#bb0000")
        self.Button3.configure(activeforeground="white")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#ff0000")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        photo_location = "../Users/Asvin/Desktop/outline_delete_black_24dp.png"
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.Button3.configure(image=_img2)
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Button''')

        self.Label5_1 = tk.Label(self.top)
        self.Label5_1.place(relx=0.422, rely=0.014, height=36, width=94)
        self.Label5_1.configure(activebackground="#f9f9f9")
        self.Label5_1.configure(activeforeground="black")
        self.Label5_1.configure(background="#737373")
        self.Label5_1.configure(disabledforeground="#a3a3a3")
        self.Label5_1.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label5_1.configure(foreground="#ffffff")
        self.Label5_1.configure(highlightbackground="#d9d9d9")
        self.Label5_1.configure(highlightcolor="black")
        self.Label5_1.configure(text='''INVOICE_NUM''')

        self.Label5_2 = tk.Label(self.top)
        self.Label5_2.place(relx=0.641, rely=0.014, height=36, width=71)
        self.Label5_2.configure(activebackground="#f9f9f9")
        self.Label5_2.configure(activeforeground="black")
        self.Label5_2.configure(background="#737373")
        self.Label5_2.configure(disabledforeground="#a3a3a3")
        self.Label5_2.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label5_2.configure(foreground="#ffffff")
        self.Label5_2.configure(highlightbackground="#d9d9d9")
        self.Label5_2.configure(highlightcolor="black")
        self.Label5_2.configure(text='''GR_NUM''')

        self.Label5_3 = tk.Label(self.top)
        self.Label5_3.place(relx=0.75, rely=0.014, height=36, width=102)
        self.Label5_3.configure(activebackground="#f9f9f9")
        self.Label5_3.configure(activeforeground="black")
        self.Label5_3.configure(background="#737373")
        self.Label5_3.configure(disabledforeground="#a3a3a3")
        self.Label5_3.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label5_3.configure(foreground="#ffffff")
        self.Label5_3.configure(highlightbackground="#d9d9d9")
        self.Label5_3.configure(highlightcolor="black")
        self.Label5_3.configure(text='''YARN SUPPLIER''')

        self.Label5_4 = tk.Label(self.top)
        self.Label5_4.place(relx=0.719, rely=0.153, height=36, width=71)
        self.Label5_4.configure(activebackground="#f9f9f9")
        self.Label5_4.configure(activeforeground="black")
        self.Label5_4.configure(background="#737373")
        self.Label5_4.configure(disabledforeground="#a3a3a3")
        self.Label5_4.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label5_4.configure(foreground="#ffffff")
        self.Label5_4.configure(highlightbackground="#d9d9d9")
        self.Label5_4.configure(highlightcolor="black")
        self.Label5_4.configure(text='''NET_WT''')

        self.Label5_5 = tk.Label(self.top)
        self.Label5_5.place(relx=0.82, rely=0.153, height=36, width=84)
        self.Label5_5.configure(activebackground="#f9f9f9")
        self.Label5_5.configure(activeforeground="black")
        self.Label5_5.configure(background="#737373")
        self.Label5_5.configure(cursor="fleur")
        self.Label5_5.configure(disabledforeground="#a3a3a3")
        self.Label5_5.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label5_5.configure(foreground="#ffffff")
        self.Label5_5.configure(highlightbackground="#d9d9d9")
        self.Label5_5.configure(highlightcolor="black")
        self.Label5_5.configure(text='''INVOICE_PR''')

        self.Entry5 = tk.Entry(self.top)
        self.Entry5.place(relx=0.445, rely=0.208, height=30, relwidth=0.113)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="-family {Courier New} -size 10 -weight bold")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="blue")
        self.Entry5.configure(selectforeground="white")
        self.Entry5.configure(textvariable=test1_support.y_s)

        self.Entry6 = tk.Entry(self.top)
        self.Entry6.place(relx=0.578, rely=0.208, height=30, relwidth=0.113)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="-family {Courier New} -size 10 -weight bold")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="blue")
        self.Entry6.configure(selectforeground="white")
        self.Entry6.configure(textvariable=test1_support.cd_num)

        self.Entry7 = tk.Entry(self.top)
        self.Entry7.place(relx=0.711, rely=0.208, height=30, relwidth=0.073)
        self.Entry7.configure(background="white")
        self.Entry7.configure(cursor="fleur")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="-family {Courier New} -size 10 -weight bold")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="blue")
        self.Entry7.configure(selectforeground="white")
        self.Entry7.configure(textvariable=test1_support.n_w)

        self.Entry8 = tk.Entry(self.top)
        self.Entry8.place(relx=0.805, rely=0.208, height=30, relwidth=0.097)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="-family {Courier New} -size 10 -weight bold")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(highlightbackground="#d9d9d9")
        self.Entry8.configure(highlightcolor="black")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(selectbackground="blue")
        self.Entry8.configure(selectforeground="white")
        self.Entry8.configure(textvariable=test1_support.inv_pr)

        self.TCombobox5 = ttk.Combobox(self.top)
        self.TCombobox5.place(relx=0.727, rely=0.069, relheight=0.042
                , relwidth=0.12)
        self.value_list = L5
        self.TCombobox5.configure(values=self.value_list)
        self.TCombobox5.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.TCombobox5.configure(textvariable=test1_support.combobox5)
        self.TCombobox5.configure(takefocus="")

        self.Button4 = tk.Button(self.top)
        self.Button4.place(relx=0.133, rely=0.278, height=44, width=47)
        self.Button4.configure(activebackground="#00d9d9")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#00ffff")
        self.Button4.configure(command=test1_support.calend)
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        photo_location = "../Users/Asvin/Desktop/outline_edit_calendar_black_36dp.png"
        global _img3
        _img3 = tk.PhotoImage(file=photo_location)
        self.Button4.configure(image=_img3)
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Button''')

        self.Button5 = tk.Button(self.top)
        self.Button5.place(relx=0.18, rely=0.278, height=44, width=47)
        self.Button5.configure(activebackground="#d9d900")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#ffff00")
        self.Button5.configure(command=test1_support.calend)
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        photo_location = "../Users/Asvin/Desktop/outline_check_black_36dp.png"
        global _img4
        _img4 = tk.PhotoImage(file=photo_location)
        self.Button5.configure(image=_img4)
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''Button''')

        self.Button6 = tk.Button(self.top)
        self.Button6.place(relx=0.891, rely=0.278, height=44, width=47)
        self.Button6.configure(activebackground="#ca6500")
        self.Button6.configure(activeforeground="white")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#ff8000")
        self.Button6.configure(command=test1_support.focus)
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        photo_location = "../Users/Asvin/Desktop/outline_star_border_black_24dp.png"
        global _img5
        _img5 = tk.PhotoImage(file=photo_location)
        self.Button6.configure(image=_img5)
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''Button''')

# def start_up():
#     test1_support.main()

if __name__ == '__main__':
    vp_start_gui()




